### ISSUE TITLE
Dense graph case

### ISSUE THREAD

**Issue by sananand007** [chncyhn/simulated-annealing-tsp#1]
What you are doing below is calculating an Adjacency matrix with distances, for this case with just 45 nodes, it is good, what about the case if this is a graph with 500,000 nodes, any ideas? 

```
def to_dist_matrix(self, coords):
        """
        Returns nxn nested list from a list of length n
        Used as distance matrix: mat[i][j] is the distance between node i and j
        'coords' has the structure [[x1,y1],...[xn,yn]]
        """
        n = len(coords)
        mat = [[self.dist(coords[i], coords[j]) for i in range(n)] for j in range(n)]
        return mat
```

**Comment by chncyhn** [comment]
Hey @sananand007 , indeed this is a O(n^2) memory approach, which would break with 500K nodes.  
  
It would be quite simple to handle a case like that actually. The simulated annealing algorithm used in this project only needs a certain candidate TSP path's fitness (i.e. total distance) to be calculated. So, you could just skip building a matrix like this, and calculate only the required distances between connected nodes in the current solution path.    
  
So the `fitness()` function would look something like this:  
  
```
def fitness(self, solution):
    n = len(solution)
    cur_fit = 0
    for i in range(n):
        cur_fit += eucledean_distance(solution[i % n], solution[(i + 1) % n])
    return cur_fit
```  
  
The initial greedy solution building would also need to be adjusted a bit like this, but that would also be easy.

**Comment by chncyhn** [comment]
Thanks for pointing it out, I should update the code of this repo a bit. 🙂

**Comment by chncyhn** [comment]
@sananand007 FYI I have pushed a commit that removes the distance matrix, so there is no quadratic space requirement anymore. 👍 
  
The nearest neighbours part is still quadratic in run time complexity however, so with 500K nodes it would take a  quite significant time. It would be possible to use a structure like [KD-Tree](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KDTree.html) to speed up from O(N^2) to O(N log N). Also the annealing part could be sped up for a case with 500K nodes by using a structure such as linked lists to be able to quickly reverse parts of the solution path, and the total distance/fitness calculation can be tracked by the changes/diffs as new solutions are explored, instead of calculating the cost of the path from scratch (which does a lot of double counting).  
  
However, I think these might be too complex for the purposes of this repo.

**Comment by sananand007** [comment]
thanks @chncyhn I will take a look further to see how I can use this for large graphs and TSP solvers . thanks for the quick response
